/**
 * Risk-theta chart: score distribution, tail probabilities, and mean-variance frontier.
 *
 * Data source: exact forward-DP PMFs (not Monte Carlo), one per theta value.
 * Generated by: python3 treatise/scripts/gen-exact-data.py
 * Input: outputs/density/density_*.json (from solver/src/bin/density_sweep)
 * Output: treatise/data/kde_curves.json (exact PMFs), sweep_summary.json (stats)
 *
 * Tail probabilities (P(≤100), P(≥360)) are computed by trapezoidal integration
 * of the exact PMF. These are true probabilities, not sample-based estimates.
 */
import { DataLoader } from '../data-loader.js';
import {
  createChart, tooltip, drawAxis, thetaColor, formatTheta,
  getTextColor, getMutedColor, getGridColor, COLORS,
} from '../yatzy-viz.js';
// Tail integration lives in /yatzy/shared/score-prob.js so the treatise chart
// and the standalone Probabilities tab share one implementation.
import { integrateTail } from '/yatzy/shared/score-prob.js';

export async function initRiskTheta() {
  const [kdeCurves, summaryData] = await Promise.all([
    DataLoader.kdeCurves(),
    DataLoader.sweepSummary(),
  ]);

  const container = document.getElementById('chart-risk-theta');
  if (!container) return;

  // Build lookup: theta -> { points: [{x,y}], mean, std, min, max }
  // Filter to ±0.4 range for clean simulation data
  const curves = kdeCurves
    .filter(entry => entry.theta >= -0.401 && entry.theta <= 0.401)
    .map(entry => {
      const points = entry.score.map((s, i) => ({ x: s, y: entry.density[i] }));
      const summary = summaryData.find(d => Math.abs(d.theta - entry.theta) < 0.001);
      return {
        theta: entry.theta,
        points,
        mean: summary ? summary.mean : 0,
        std: summary ? summary.std : 0,
      };
    });

  const refIdx = curves.findIndex(c => Math.abs(c.theta) < 0.001);

  // Slider
  const controls = container.querySelector('.chart-controls');
  const slider = controls.querySelector('.chart-slider');
  const valueDisplay = controls.querySelector('.slider-value');

  slider.min = 0;
  slider.max = curves.length - 1;
  const defaultIdx = refIdx >= 0 ? refIdx : 0;
  slider.value = defaultIdx;

  // Frontier data: match slider's theta range
  const thetaMin = curves[0].theta;
  const thetaMax = curves[curves.length - 1].theta;
  const frontierData = summaryData
    .filter(d => d.theta >= thetaMin - 0.01 && d.theta <= thetaMax + 0.01)
    .sort((a, b) => a.theta - b.theta);

  // Fixed scales for distribution
  const xDomain = [0, 400];
  const yDomain = [0, 0.015];

  // Precompute reference values
  const thresholds = [
    { score: 100, above: false, label: 'P(≤ 100)', bad: true },
    { score: 200, above: false, label: 'P(≤ 200)', bad: true },
    { score: 248.4, above: true, label: 'P(≥ EV)', bad: false },
    { score: 310, above: true,  label: 'P(≥ 310)', bad: false },
    { score: 360, above: true,  label: 'P(≥ 360)', bad: false },
  ];
  const refProbs = thresholds.map(t =>
    integrateTail(curves[refIdx].points, t.score, t.above));

  function render(idx) {
    const cur = curves[idx];
    valueDisplay.textContent = formatTheta(cur.theta);

    renderDistribution(cur, curves, idx);
    renderTailStats(cur);
    renderFrontier(cur);
  }

  // ── Distribution chart (top) ──────────────────────────────────────

  function renderDistribution(cur, allCurves, idx) {
    const chart = createChart('chart-risk-theta-distribution', { aspectRatio: 0.5 });
    if (!chart) return;
    const { g, width, height } = chart;

    const x = d3.scaleLinear().domain(xDomain).range([0, width]);
    const y = d3.scaleLinear().domain(yDomain).range([height, 0]);

    // Grid
    g.append('g').attr('class', 'grid')
      .selectAll('line').data(y.ticks(5)).join('line')
      .attr('x1', 0).attr('x2', width)
      .attr('y1', d => y(d)).attr('y2', d => y(d))
      .attr('stroke', getGridColor())
      .attr('stroke-dasharray', '2,3');

    const line = d3.line().x(d => x(d.x)).y(d => y(d.y)).curve(d3.curveBasis);

    // Background curves
    for (let i = 0; i < allCurves.length; i++) {
      if (i === idx) continue;
      g.append('path')
        .datum(allCurves[i].points)
        .attr('d', line)
        .attr('fill', 'none')
        .attr('stroke', thetaColor(allCurves[i].theta))
        .attr('stroke-width', 1)
        .attr('opacity', 0.15);
    }

    // Selected curve: filled area + bold line
    const color = thetaColor(cur.theta);

    g.append('path')
      .datum(cur.points)
      .attr('d', d3.area().x(d => x(d.x)).y0(height).y1(d => y(d.y)).curve(d3.curveBasis))
      .attr('fill', color)
      .attr('opacity', 0.12);

    g.append('path')
      .datum(cur.points)
      .attr('d', line)
      .attr('fill', 'none')
      .attr('stroke', color)
      .attr('stroke-width', 2.5);

    // ±1σ…±4σ lines. Same dashed style as the mean line so the spread reads
    // clearly; higher sigma is progressively fainter to keep the mean dominant
    // while still showing how far the tail reaches at higher θ. (±4σ often
    // falls past the 400 domain and is clipped; that itself signals the tail
    // running off the achievable score range.)
    const sigmaLevels = [
      { k: 1, opacity: 0.7 },
      { k: 2, opacity: 0.52 },
      { k: 3, opacity: 0.36 },
      { k: 4, opacity: 0.24 },
    ];
    for (const { k, opacity } of sigmaLevels) {
      for (const sign of [-1, 1]) {
        const sx = cur.mean + sign * k * cur.std;
        if (sx <= 0 || sx >= 400) continue;
        g.append('line')
          .attr('x1', x(sx)).attr('x2', x(sx))
          .attr('y1', 0).attr('y2', height)
          .attr('stroke', color)
          .attr('stroke-width', 1.5)
          .attr('stroke-dasharray', '5,3')
          .attr('opacity', opacity);
        g.append('text')
          .attr('x', x(sx) + (sign > 0 ? 4 : -4)).attr('y', height - 6)
          .attr('text-anchor', sign > 0 ? 'start' : 'end')
          .attr('fill', color)
          .attr('opacity', Math.min(opacity + 0.2, 0.95))
          .style('font-size', '9px')
          .text(`${sign > 0 ? '+' : '−'}${k}σ`);
      }
    }

    // Mean line (heaviest, so it stays dominant over the sigma lines)
    g.append('line')
      .attr('x1', x(cur.mean)).attr('x2', x(cur.mean))
      .attr('y1', 0).attr('y2', height)
      .attr('stroke', color)
      .attr('stroke-width', 2.25)
      .attr('stroke-dasharray', '5,3');

    g.append('text')
      .attr('x', x(cur.mean) + 5).attr('y', 14)
      .attr('fill', color)
      .style('font-size', '11px')
      .text(`mean = ${cur.mean.toFixed(1)}`);

    // Axes
    drawAxis(g.append('g').attr('transform', `translate(0,${height})`), x, 'bottom', 'Score');
    // Y-axis: label only, no tick values
    const yG = g.append('g').call(d3.axisLeft(y).ticks(0).tickSize(0));
    yG.select('.domain').attr('stroke', getGridColor());
    yG.append('text').attr('transform', 'rotate(-90)')
      .attr('x', -height / 2).attr('y', -35)
      .attr('fill', getMutedColor()).attr('text-anchor', 'middle')
      .style('font-size', '12px').text('Density');

    // Crosshair tooltip
    const tt = tooltip(container);
    const bisect = d3.bisector(d => d.x).left;

    const overlay = g.append('rect')
      .attr('width', width).attr('height', height)
      .attr('fill', 'none').attr('pointer-events', 'all');

    const crosshairLine = g.append('line')
      .attr('y1', 0).attr('y2', height)
      .attr('stroke', getMutedColor())
      .attr('stroke-width', 1)
      .attr('stroke-dasharray', '3,3')
      .attr('opacity', 0);

    overlay
      .on('mousemove', (event) => {
        const [mx] = d3.pointer(event);
        const xVal = x.invert(mx);
        const i = bisect(cur.points, xVal);
        const d = cur.points[Math.min(i, cur.points.length - 1)];
        if (!d) return;
        crosshairLine.attr('x1', x(d.x)).attr('x2', x(d.x)).attr('opacity', 0.6);
        tt.show(
          `<div class="tt-label">Score: ${d.x.toFixed(0)}</div>
           <div>Density: <span class="tt-value">${d.y.toFixed(4)}</span></div>
           <div>Mean: ${cur.mean.toFixed(1)}, Std: ${cur.std.toFixed(1)}</div>`,
          event
        );
      })
      .on('mouseleave', () => {
        crosshairLine.attr('opacity', 0);
        tt.hide();
      });
  }

  // ── Threshold probability stats (middle) ──────────────────────────

  /** Format a probability (0-1) for display. Uses scientific notation for tiny values. */
  function formatProb(p) {
    const pct = p * 100;
    if (pct >= 0.1) return `${pct.toFixed(1)}%`;
    if (p === 0) return '0';
    const exp = Math.floor(Math.log10(p));
    const coeff = p / Math.pow(10, exp);
    return `${coeff.toFixed(1)}&thinsp;&times;&thinsp;10<sup>${exp}</sup>`;
  }

  function renderTailStats(cur) {
    const el = document.getElementById('chart-risk-theta-stats');
    if (!el) return;

    function probStat(idx, useSciNotation) {
      const prob = integrateTail(cur.points, thresholds[idx].score, thresholds[idx].above);
      const pct = prob * 100;
      const refPct = refProbs[idx] * 100;
      const relChange = refPct > 0.01 ? ((pct - refPct) / refPct) * 100 : 0;
      const isWorse = thresholds[idx].bad ? relChange > 0.5 : relChange < -0.5;
      const isBetter = thresholds[idx].bad ? relChange < -0.5 : relChange > 0.5;
      const color = isWorse ? COLORS.riskSeeking : isBetter ? '#2ca02c' : getMutedColor();
      const valueStr = useSciNotation ? formatProb(prob) : `${pct.toFixed(1)}%`;
      let changeStr;
      if (useSciNotation) {
        const ratio = refProbs[idx] > 0 ? prob / refProbs[idx] : 0;
        let ratioStr;
        if (ratio === 0) ratioStr = '—';
        else if (Math.abs(ratio - 1) < 0.05) ratioStr = '1&times;';
        else if (ratio >= 1) ratioStr = `${ratio.toFixed(1)}&times;`;
        else ratioStr = `1/${(1 / ratio).toFixed(0)}&times;`;
        changeStr = `${ratioStr} vs &theta;=0`;
      } else {
        const sign = relChange > 0 ? '+' : '';
        changeStr = `${sign}${relChange.toFixed(0)}% vs &theta;=0`;
      }
      return `<div class="tail-stat">
        <div class="tail-stat-value">${valueStr}</div>
        <div class="tail-stat-change" style="color:${color}">${changeStr}</div>
        <div class="tail-stat-label">${thresholds[idx].label}</div>
      </div>`;
    }

    el.innerHTML =
      probStat(0, true) +
      probStat(1, false) +
      probStat(2, false) +
      probStat(3, false) +
      probStat(4, true);
  }

  // ── Mean-variance frontier (bottom) ───────────────────────────────

  function renderFrontier(cur) {
    const chart = createChart('chart-risk-theta-frontier', { aspectRatio: 0.45 });
    if (!chart) return;
    const { g, width, height } = chart;

    const x = d3.scaleLinear()
      .domain([d3.min(frontierData, d => d.std) - 1, d3.max(frontierData, d => d.std) + 1])
      .range([0, width]);
    const y = d3.scaleLinear()
      .domain([d3.min(frontierData, d => d.mean) - 5, d3.max(frontierData, d => d.mean) + 5])
      .range([height, 0]);

    // Grid
    g.append('g').selectAll('line').data(y.ticks(5)).join('line')
      .attr('x1', 0).attr('x2', width)
      .attr('y1', d => y(d)).attr('y2', d => y(d))
      .attr('stroke', getGridColor()).attr('stroke-dasharray', '2,3');

    g.append('g').selectAll('line').data(x.ticks(6)).join('line')
      .attr('x1', d => x(d)).attr('x2', d => x(d))
      .attr('y1', 0).attr('y2', height)
      .attr('stroke', getGridColor()).attr('stroke-dasharray', '2,3');

    // Path segments
    for (let i = 0; i < frontierData.length - 1; i++) {
      const d0 = frontierData[i], d1 = frontierData[i + 1];
      g.append('line')
        .attr('x1', x(d0.std)).attr('y1', y(d0.mean))
        .attr('x2', x(d1.std)).attr('y2', y(d1.mean))
        .attr('stroke', thetaColor((d0.theta + d1.theta) / 2))
        .attr('stroke-width', 2.5)
        .attr('stroke-linecap', 'round');
    }

    // All dots
    g.selectAll('.mv-dot')
      .data(frontierData)
      .join('circle')
      .attr('cx', d => x(d.std)).attr('cy', d => y(d.mean))
      .attr('r', 3.5)
      .attr('fill', d => thetaColor(d.theta));

    // θ=0 reference marker
    const t0 = frontierData.find(d => Math.abs(d.theta) < 0.001);
    if (t0) {
      g.append('circle')
        .attr('cx', x(t0.std)).attr('cy', y(t0.mean))
        .attr('r', 5)
        .attr('fill', 'none')
        .attr('stroke', getMutedColor())
        .attr('stroke-width', 1.5)
        .attr('stroke-dasharray', '2,2');
      g.append('text')
        .attr('x', x(t0.std) + 8).attr('y', y(t0.mean) - 8)
        .attr('fill', getMutedColor())
        .style('font-size', '10px')
        .text('θ = 0');
    }

    // Current θ highlight
    const curPt = frontierData.find(d => Math.abs(d.theta - cur.theta) < 0.001);
    if (curPt) {
      const color = thetaColor(cur.theta);
      g.append('circle')
        .attr('cx', x(curPt.std)).attr('cy', y(curPt.mean))
        .attr('r', 8)
        .attr('fill', 'none')
        .attr('stroke', color)
        .attr('stroke-width', 2);
      g.append('circle')
        .attr('cx', x(curPt.std)).attr('cy', y(curPt.mean))
        .attr('r', 4)
        .attr('fill', color)
        .attr('stroke', 'white')
        .attr('stroke-width', 1.5);
    }

    // Branch labels
    const ra = frontierData.find(d => Math.abs(d.theta + 0.3) < 0.01) || frontierData[0];
    g.append('text')
      .attr('x', x(ra.std) - 8).attr('y', y(ra.mean) + 16)
      .attr('text-anchor', 'end')
      .attr('fill', COLORS.riskAverse)
      .style('font-size', '10px')
      .text('risk-averse \u2190');

    const rs = frontierData.find(d => Math.abs(d.theta - 0.3) < 0.01) || frontierData[frontierData.length - 1];
    g.append('text')
      .attr('x', x(rs.std) + 8).attr('y', y(rs.mean) + 16)
      .attr('fill', COLORS.riskSeeking)
      .style('font-size', '10px')
      .text('\u2192 risk-seeking');

    // Axes
    drawAxis(
      g.append('g').attr('transform', `translate(0,${height})`),
      x, 'bottom', 'Standard deviation (risk)'
    );
    drawAxis(g, y, 'left', 'Mean score (return)');

    // Tooltip on hover
    const tt = tooltip(container);
    g.selectAll('.mv-hover')
      .data(frontierData)
      .join('circle')
      .attr('cx', d => x(d.std)).attr('cy', d => y(d.mean))
      .attr('r', 10)
      .attr('fill', 'none')
      .attr('pointer-events', 'all')
      .attr('cursor', 'pointer')
      .on('mousemove', (event, d) => {
        const dm = d.mean - t0.mean, ds = d.std - t0.std;
        const fm = v => (v >= 0 ? '+' : '') + v.toFixed(1);
        tt.show(
          `<div class="tt-label" style="font-variant-numeric:tabular-nums">\u03b8 = ${formatTheta(d.theta)}</div>
           <div style="font-variant-numeric:tabular-nums">Mean: <span class="tt-value">${d.mean.toFixed(1)}</span> <span style="opacity:0.6">(${fm(dm)})</span></div>
           <div style="font-variant-numeric:tabular-nums">Std: <span class="tt-value">${d.std.toFixed(1)}</span> <span style="opacity:0.6">(${fm(ds)})</span></div>
           <div style="font-variant-numeric:tabular-nums">p5: ${d.p5}, p50: ${d.p50}, p95: ${d.p95}</div>`,
          event
        );
      })
      .on('mouseleave', () => tt.hide());
  }

  render(+slider.value);
  slider.addEventListener('input', () => render(+slider.value));
}
