services:
  yatzy-frontend:
    build: ./frontend
    container_name: yatzy-frontend
    restart: always
    networks:
      - shared_network
    ports:
      - "8090:8090"  # Map frontend port to host
    expose:
      - 8090
    environment:
      - API_BASE_URL=http://localhost:9000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090" ]
      interval: 30s
      timeout: 10s
      retries: 3

  yatzy-backend:
    build: ./backend
    container_name: yatzy-backend
    restart: always
    ports:
      - "9000:9000"  # Map backend port to host
    networks:
      - shared_network
    expose:
      - 9000
    environment:
      - API_PORT=9000  # Environment variable for backend port
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_network:
    external: true