from utils import combinations

REROLL_INDEX = 0

DICES_COUNT = 5
DICE_RANGE_START = REROLL_INDEX + 1
DICE_RANGE_END = DICE_RANGE_START + DICES_COUNT

COMBINATIONS_COUNT = len(combinations)

ACTION_SCORING_RANGE_START = DICE_RANGE_END
ACTION_SCORING_RANGE_END = ACTION_SCORING_RANGE_START + COMBINATIONS_COUNT

STATE_ALLOWED_RANGE_START = DICE_RANGE_END
STATE_ALLOWED_RANGE_END = STATE_ALLOWED_RANGE_START + COMBINATIONS_COUNT

STATE_SCORED_RANGE_START = STATE_ALLOWED_RANGE_END
STATE_SCORED_RANGE_END = STATE_SCORED_RANGE_START + COMBINATIONS_COUNT
